name: Run tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
      - name: Test with pytest
        run: |
          ls -a
          pytest example.py
